"""add librecrawl raw crawl tables

Revision ID: d8c88ac452ce
Revises: b29d5f31a7d4
Create Date: 2026-08-02 16:34:17.068473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c88ac452ce'
down_revision = 'b29d5f31a7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_page_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('target_domain', sa.String(length=255), nullable=True),
    sa.Column('target_status', sa.Integer(), nullable=True),
    sa.Column('placement', sa.String(length=64), nullable=True),
    sa.Column('discovered_at', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_page_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_page_links_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_page_links_source_url'), ['source_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_page_links_target_url'), ['target_url'], unique=False)

    op.create_table('crawl_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1', sa.Text(), nullable=True),
    sa.Column('h2', sa.JSON(), nullable=True),
    sa.Column('h3', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=64), nullable=True),
    sa.Column('charset', sa.String(length=64), nullable=True),
    sa.Column('viewport', sa.Text(), nullable=True),
    sa.Column('robots', sa.Text(), nullable=True),
    sa.Column('meta_tags', sa.JSON(), nullable=True),
    sa.Column('og_tags', sa.JSON(), nullable=True),
    sa.Column('twitter_tags', sa.JSON(), nullable=True),
    sa.Column('json_ld', sa.JSON(), nullable=True),
    sa.Column('analytics', sa.JSON(), nullable=True),
    sa.Column('hreflang', sa.JSON(), nullable=True),
    sa.Column('schema_org', sa.JSON(), nullable=True),
    sa.Column('redirects', sa.JSON(), nullable=True),
    sa.Column('linked_from', sa.JSON(), nullable=True),
    sa.Column('external_links', sa.Integer(), nullable=True),
    sa.Column('internal_links', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('javascript_rendered', sa.Boolean(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('crawled_at', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_pages_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_pages_url'), ['url'], unique=False)

    op.create_table('crawl_page_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_page_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_page_images_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_page_images_page_url'), ['page_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_page_images_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('crawl_page_structured_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('schema_type', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_page_structured_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_page_structured_data_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_page_structured_data_page_url'), ['page_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_page_structured_data_snapshot_id'), ['snapshot_id'], unique=False)

    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('librecrawl_crawl_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_column('librecrawl_crawl_id')

    with op.batch_alter_table('crawl_page_structured_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_page_structured_data_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_page_structured_data_page_url'))
        batch_op.drop_index(batch_op.f('ix_crawl_page_structured_data_page_id'))

    op.drop_table('crawl_page_structured_data')
    with op.batch_alter_table('crawl_page_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_page_images_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_page_images_page_url'))
        batch_op.drop_index(batch_op.f('ix_crawl_page_images_page_id'))

    op.drop_table('crawl_page_images')
    with op.batch_alter_table('crawl_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_pages_url'))
        batch_op.drop_index(batch_op.f('ix_crawl_pages_snapshot_id'))

    op.drop_table('crawl_pages')
    with op.batch_alter_table('crawl_page_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_page_links_target_url'))
        batch_op.drop_index(batch_op.f('ix_crawl_page_links_source_url'))
        batch_op.drop_index(batch_op.f('ix_crawl_page_links_snapshot_id'))

    op.drop_table('crawl_page_links')
    # ### end Alembic commands ###
